<?php
global $PROXMOXNETTYPE;

define('PROXMOX_TYPE_VM', 1);
define('PROXMOX_TYPE_VMCLONE', 2);
define('PROXMOX_TYPE_CT', 3);

$PROXMOXTYPE = array (
	PROXMOX_TYPE_VM => 'Virtual Machine',
	PROXMOX_TYPE_VMCLONE => 'VM Clone',
	PROXMOX_TYPE_CT => 'CT',
);

define('PROXMOX_NETTYPE_E1000', 1);
define('PROXMOX_NETTYPE_VIRTIO', 2);
define('PROXMOX_NETTYPE_RTL8139', 3);
define('PROXMOX_NETTYPE_VMXNET3', 4);

$PROXMOXNETTYPE = array (
	PROXMOX_NETTYPE_E1000 => 'e1000',
	PROXMOX_NETTYPE_VIRTIO => 'virtio',
	PROXMOX_NETTYPE_RTL8139 => 'rtl8139',
	PROXMOX_NETTYPE_VMXNET3 => 'vmxnet3',
);

if(isset($SMARTY))
{
	$SMARTY->assign('_PROXMOXNETTYPE', $PROXMOXNETTYPE);
	$SMARTY->assign('_PROXMOXTYPE', $PROXMOXTYPE);
}
?>
